import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// created by chatgpt
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString("tr-TR", options);

  const time = date.toLocaleTimeString("tr-TR", {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

// Capitalize
export function capitalize(str: string) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// Random Community
export function getRandomCommunities(communities: any, count: any) {
  const shuffled = communities.sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}
