import type { profiles, communities, threads } from "../server/db/schema";
export type Profile = typeof profiles.$inferSelect;
export type Community = typeof communities.$inferSelect;
export type CommunitySummary = Community & { memberCount: number; joined: boolean };
export type UploadImageResult = { objectPath: string; url: string; mimeType: "image/jpeg" | "image/png" | "image/webp"; byteSize: number; width: number; height: number };
export type PostMedia = UploadImageResult & { id: string; altText: string; position: number };
export type JobShareSummary = Pick<typeof import("../server/db/schema").jobs.$inferSelect, "id" | "title" | "company" | "location" | "workMode" | "employmentType" | "deadline"> & { status: "published" | "closed" };
export type JobReference = { state: "available"; job: JobShareSummary } | { state: "unavailable" };
export type Post = Omit<typeof threads.$inferSelect, "resourceKind" | "jobId"> & {
  jobReference?: JobReference | null;
  author: Profile;
  community: Community | null;
  likeCount: number;
  replyCount: number;
  liked: boolean;
  bookmarked: boolean;
  media: PostMedia[];
  reposted: boolean;
  repostCount: number;
  replyAuthors: { id: string; image: string }[];
};
export type ThreadPage = { post: Post; replies: Post[]; hasMore: boolean };
export type FeedPage = { posts: Post[]; hasMore: boolean; snapshot?: string };
export type BookmarksPage = { posts: Post[]; nextCursor: string | null };
export type FollowState = { following: boolean; followerCount: number; followingCount: number };
export type ProfileListPage = { profiles: Profile[]; nextCursor: string | null };
export type ProfilePage = FollowState & { profile: Profile; posts: Post[]; hasMore: boolean; postCount: number };
export type CommunityPage = { community: CommunitySummary; owner: Profile; members: Profile[]; posts: Post[]; hasMore: boolean };
export type Me = { profile: Profile; communities: CommunitySummary[]; suggestedCommunities: CommunitySummary[] };
export type SearchResults = { query: string; posts: Post[]; people: Profile[]; communities: CommunitySummary[] };
type NotificationBase = { id: string; createdAt: string; readAt: string | null; actor: Profile };
export type Notification = NotificationBase & ({ kind: "follow"; post: null } | { kind: "reply"; post: Post | null } | { kind: "like"; post: Post | null });
export type NotificationPage = { notifications: Notification[]; nextCursor: string | null; unreadCount: number };
export type RepostState = { reposted: boolean; repostCount: number };
export type TimelineEntry = { post: Post; repost: { actor: Profile; createdAt: string } | null };
export type TimelinePage = { entries: TimelineEntry[]; nextCursor: string | null; snapshot: string; followingCount?: number };
export type AccountList = { id: string; ownerId: string; name: string; description: string; createdAt: string; updatedAt: string; memberCount: number };
export type AccountListsPage = { lists: AccountList[]; nextCursor: string | null };
export type SavedSearch = { id: string; ownerId: string; query: string; tab: "posts" | "people" | "communities"; createdAt: string };
export type SavedSearchesPage = { searches: SavedSearch[]; nextCursor: string | null };

export type ExplorePage = SearchResults & { tab: "posts" | "people" | "communities"; nextCursor: string | null };
export type ResourcePage<T> = { items: T[]; nextCursor: string | null };
export type Job = typeof import("../server/db/schema").jobs.$inferSelect & { publisher: Profile; saved: boolean };
export type Article = typeof import("../server/db/schema").articles.$inferSelect & { publisher: Profile };
export type TextDraft = Omit<typeof import("../server/db/schema").textDrafts.$inferSelect, "resourceKind" | "jobId"> & { resourceKind?: "job" | null; jobId?: string | null; jobReference?: JobReference | null; available: boolean; unavailableReason: string | null };
export type Preferences = { reducedMotion: boolean; defaultFeed: "all" | "latest" | "following" | "communities"; notificationKind: "all" | "reply" | "like" | "follow" };
export type CreatorAnalytics = { postCount: number; likesReceived: number; repliesReceived: number; repostsReceived: number; followerCount: number; from: string | null; to: string | null };
export type CommunityEvent = typeof import("../server/db/schema").communityEvents.$inferSelect & { publisher: Profile; community: Community; rsvped: boolean };
