import type { profiles, communities, threads } from "../server/db/schema";
export type Profile = typeof profiles.$inferSelect;
export type Community = typeof communities.$inferSelect;
export type CommunitySummary = Community & { memberCount: number; joined: boolean };
export type UploadImageResult = { objectPath: string; url: string; mimeType: "image/jpeg" | "image/png" | "image/webp"; byteSize: number; width: number; height: number };
export type PostMedia = UploadImageResult & { id: string; altText: string; position: number };
export type Post = typeof threads.$inferSelect & {
  author: Profile;
  community: Community | null;
  likeCount: number;
  replyCount: number;
  liked: boolean;
  bookmarked: boolean;
  media: PostMedia[];
  reposted: boolean;
  repostCount: number;
  replyAuthors: { id: string; image: string }[];
};
export type ThreadPage = { post: Post; replies: Post[]; hasMore: boolean };
export type FeedPage = { posts: Post[]; hasMore: boolean; snapshot?: string };
export type BookmarksPage = { posts: Post[]; nextCursor: string | null };
export type FollowState = { following: boolean; followerCount: number; followingCount: number };
export type ProfileListPage = { profiles: Profile[]; nextCursor: string | null };
export type ProfilePage = FollowState & { profile: Profile; posts: Post[]; hasMore: boolean; postCount: number };
export type CommunityPage = { community: CommunitySummary; owner: Profile; members: Profile[]; posts: Post[]; hasMore: boolean };
export type Me = { profile: Profile; communities: CommunitySummary[]; suggestedCommunities: CommunitySummary[] };
export type SearchResults = { query: string; posts: Post[]; people: Profile[]; communities: CommunitySummary[] };
type NotificationBase = { id: string; createdAt: string; readAt: string | null; actor: Profile };
export type Notification = NotificationBase & ({ kind: "follow"; post: null } | { kind: "reply"; post: Post | null } | { kind: "like"; post: Post | null });
export type NotificationPage = { notifications: Notification[]; nextCursor: string | null; unreadCount: number };
export type RepostState = { reposted: boolean; repostCount: number };
export type TimelineEntry = { post: Post; repost: { actor: Profile; createdAt: string } | null };
export type TimelinePage = { entries: TimelineEntry[]; nextCursor: string | null; snapshot: string; followingCount?: number };
